version: "3.1"

services:
  # mysql database container
  db:
    image: mysql:5.7.16
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  # wordpress container
  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content:cached
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      DEVELOPMENT: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: exampledb
